 
all: exemple1 exemple2 exemple3 exemple4 exemple5 exemple6 exemple7 exemple8 exemple9 exemple10 exercice1

exemple1 : exemple1.c
	gcc exemple1.c -o exemple1

exemple2 : exemple2.c
	gcc exemple2.c -o exemple2

exemple3 : exemple3.c
	gcc exemple3.c -o exemple3

exemple4 : exemple4.c
	gcc exemple4.c -o exemple4

exemple5 : exemple5.c
	gcc exemple5.c -o exemple5

exemple6 : exemple6.c
	gcc exemple6.c -o exemple6

exemple7 : exemple7.c
	gcc exemple7.c -o exemple7

exemple8 : exemple8.c
	gcc exemple8.c -o exemple8

exemple9 : exemple9.c
	gcc exemple9.c -o exemple9

exemple10 : exemple10.c
	gcc exemple10.c -o exemple10

exercice1 : exercice1.c
	gcc exercice1.c -o exercice1

clean:
	rm exemple1 exemple2 exemple3 exemple4 exemple5 exemple6 exemple7 exemple8 exemple9 exemple10 exercice1
